require('node:dns/promises').setServers(['1.1.1.1', '8.8.8.8']);
const mongoose = require('mongoose');
const Blog = require('../src/models/Blog');
const { mongoUri, validateEnvironment } = require('../src/config');
const blogs = [
  { title: 'Building a Better Debugging Habit', category: 'Frontend', excerpt: 'A practical loop for turning confusing bugs into useful feedback.', content: '# Building a Better Debugging Habit\n\nStart by making the problem **small and observable**. Reproduce it, write down the expected result, then change one input at a time.\n\n## A lightweight loop\n\n1. Reproduce the smallest failing case.\n2. Form one testable hypothesis.\n3. Inspect the evidence before changing code.\n\nGood debugging is less about speed and more about reducing uncertainty.', tags: ['debugging', 'workflow'], readingTime: '4 min read', published: true, publishedAt: new Date('2026-01-12') },
  { title: 'What I Learned From Shipping Small', category: 'DevOps', excerpt: 'Why compact releases improve feedback, confidence, and product direction.', content: '# What I Learned From Shipping Small\n\nSmall releases let you learn from real use without betting everything on an assumption.\n\n## Keep the loop short\n\nChoose one problem, make the smallest useful change, and measure what happened. The next release becomes clearer.', tags: ['product', 'learning'], readingTime: '3 min read', published: true, publishedAt: new Date('2026-02-08') },
  { title: 'A Friendly Introduction to API Boundaries', category: 'Backend', excerpt: 'A clear separation between a browser app, an API, and a database keeps credentials safe.', content: '# A Friendly Introduction to API Boundaries\n\nA frontend should talk to an API. The API owns validation, authorization, and database access.\n\n## Why it matters\n\nKeeping credentials on the server prevents them from being bundled into the browser application and gives one place to enforce rules.', tags: ['api', 'security', 'architecture'], readingTime: '5 min read', published: true, publishedAt: new Date('2026-03-04') }
];
async function seed() { validateEnvironment(); await mongoose.connect(mongoUri); await Blog.deleteMany({}); await Blog.create(blogs); console.log(`Seeded ${blogs.length} blogs.`); await mongoose.disconnect(); }
seed().catch(async error => { console.error(error); await mongoose.disconnect(); process.exit(1); });
